---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  ports:
    - port: 80         # Port exposed by the service
      targetPort: 80   # Port on the container
  selector:
    name: voting-app-pod
    app: demo-voting-app

